### ISSUE TITLE
Potential deletions for V5

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-teaser#101]
This issue is to track features which may potentially be removed from the next major version of o-teaser. They have been chosen but they have never been used, have not been used for 6 months or more, or are broken or ineffective.

- [x] Package teasers (not available for use on FT.com since December 2017)
- [x] Small `image-position-right` variant (used in one place by FT.com)
- [x] Hero `standalone` variant (Hero teasers with images always use `center` variant which overrides this)
- [x] Hero `midslice` variant (Never used)
- [x] Hero `big-video` variant (Re-named `has-video`, #92)
- [x] Top story `standalone` variant (Has no effect)
- [x] Large portrait and large landscape (not used since November 2016)
- [x] Syndication icons (provided by n-syndication component)

**Comment by i-like-robots** [comment]
I have found the `image-position-right` variant for small teasers used on a single stream page so I will hold off removing it.

**Comment by i-like-robots** [comment]
Tricia spoke to the owners of the stream page using the `image-position-right` variant and they don't mind if we change it. So `image-position-right` is open to deletion again if we wish.

**Comment by i-like-robots** [comment]
The `image-position-right` variant has now been removed from the page so it is safe to delete.

**Comment by chee** [comment]
it looks like these were done
