### ISSUE TITLE
Potential refactors for the next major release

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/o-teaser#102]
Collecting a few ideas for some refactors that may be worth squeezing into a major release.

- [ ] Separate "themes" into "layout" and "theme" use cases
- [ ] Create a specific "footer" or "pocket" area to contain icons/hints/indicators
- [ ] Use consistent terminology between [x-teaser][1] and [o-teaser][2]
- [ ] Modifiers which target only a specific layout should be prefixed with the layout name
- [ ] Make a clean split between `--large` and `--hero` variants
- [ ] Refactor `--hero-image` variant into separate `--poster` (name?) variant
- [ ] Put `--has-video` variant video player in the same slot as the `--has-image` image (maybe?)
- [ ] Ensure output of `oTeaser()` mixin is always the same given different argument order to ensure implementers receive the intended cascade
- [x] Simplify live blog styles (#111)

CC https://github.com/Financial-Times/o-teaser/issues/101

[1]: https://github.com/Financial-Times/x-dash/blob/f96142c63351174e07d1a71526aec5b3bcf6fac6/components/x-teaser/docs/features.md
[2]: https://github.com/Financial-Times/o-teaser/blob/0438a0ab05b6d565590ef25ba1c4366218c6e581/src/scss/_variables.scss#L8

**Comment by i-like-robots** [comment]
In x-teaser we have enforced [rules][1] to ensure only one within a set conflicting modifiers may be applied to a teaser at a time. Currently we have not enforced this and so we are at the mercy of the cascade (see the final checkbox point for more on that!) so we get fun things like this, combining the "opinion" and "extra" themes:

<img width="248" alt="screen shot 2018-09-04 at 14 28 04" src="https://user-images.githubusercontent.com/271645/45035003-d4de2280-b050-11e8-8835-09e036522480.png">

[1]: https://github.com/Financial-Times/x-dash/tree/master/components/x-teaser#rules

**Comment by gvonkoss** [comment]
another example of this is the `hero-image` + `opinion` combination. 

A `hero-image` teaser _should_ look like this:
![screen shot 2018-09-05 at 15 25 08](https://user-images.githubusercontent.com/16777943/45099826-22759080-b120-11e8-836b-75b3fcf518c1.png)

When combined with opinion, it looks like this:
![screen shot 2018-09-05 at 15 19 54](https://user-images.githubusercontent.com/16777943/45099832-27d2db00-b120-11e8-8207-538b46903134.png)

But the hero-image teaser collapses into a centred hero on small viewports, so the opinion colours still need to be there:
![screen shot 2018-09-05 at 15 26 47](https://user-images.githubusercontent.com/16777943/45099865-391be780-b120-11e8-97f8-fa4947b26ffc.png)

**Comment by chee** [comment]
@Financial-Times/origami-core are we going to do these?

**Comment by notlee** [comment]
Probably not. o-teaser isn't going to be used on the new front page. I suspect a larger review/rewrite might be in store.

**Comment by chee** [comment]
this is outdated
