### ISSUE TITLE
o-teaser-header and label spacing

### ISSUE THREAD

**Issue by thurstontye** [Financial-Times/o-teaser#129]
Bug

## What
Loss of space between `o-teaser-header` and `o-labels` elements in some contexts but not all. Think it just needs some padding on `o-teaser-header a` so will raise a PR to that effect.

## Details
[example on streams](https://www.ft.com/search?q=brex)
Also at the bottom of article pages in the  [topic tracker related content] (https://www.ft.com/content/aaaf613c-768d-11e9-be7d-6d846537acab)
## Additional information
See: https://trello.com/c/CkoIA7pZ/889-padding-issue-with-topic-tracker

**Comment by thurstontye** [comment]
On reflection this may be an issue with o-labels

**Comment by notlee** [comment]
Sorry for the lack of response here. Looking at the examples I think this must have been fixed. x-dash adds the premium label within x-teaser, using a space between the end of the heading and the teaser. Let us know if this is stll an issue though
