### ISSUE TITLE
o-teaser does not display correctly on Safari 8

### ISSUE THREAD

**Issue by phiychai** [Financial-Times/o-teaser#49]
![realios_ipad_air_2](https://cloud.githubusercontent.com/assets/3500928/24554314/5ea3be5e-162d-11e7-8a3c-b8c66b57a957.jpg)

**Comment by onishiweb** [comment]
Potentially the `order` property of flexbox not working correctly

**Comment by onishiweb** [comment]
Can be fixed by the above PR in OBT
