### ISSUE TITLE
mixin overlap

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-teaser#56]
When using mixins exclusively, calling `@include oTeaser(('default', 'images'), ('hero'))` doesn't bring in all of the `hero` styling — specifically, it doesn't seem include any styling that is supported by `large`, unless `large` itself is explicitly included.

I haven't tried it with any other themes/elements, though, so could be an exception.

**Comment by gvonkoss** [comment]
Also, I've recently discovered, that for `hero` to work, the mixin parameters need to be passed in in this specific order: `('large', 'hero')`, or the styles don't build correctly (?)

**Comment by onishiweb** [comment]
Thanks for discovering this and letting us know @gvonkoss will probably aim to fix this in the next major

**Comment by gvonkoss** [comment]
more discovering! It turns out that the specific order is required for any and all layers of mixins `('large', 'hero', 'top-stories')`— I'm assuming this is because of the _order_ of the build? As in, last declared style is the valid style?
Technically that would mean that any mixins that get included after  the mixins one can include in the critical css, would overwrite the original styling?

**Comment by gvonkoss** [comment]
tag colours aren't included if the default mixin is used because they're only referenced in main.scss which is ignored if we load this silently 😩

**Comment by gvonkoss** [comment]
colors on tags (and likely general use cases for colours) don't come through on `silent` if the (for example, front page) app does not require `o-colors` directly 😞

**Comment by gvonkoss** [comment]
perhaps the option _not_ to pass in an element or a theme might be useful
