### ISSUE TITLE
Change vertical rule colour. 

### ISSUE THREAD

**Issue by draysonandstock** [Financial-Times/o-teaser#95]
![screen shot 2018-05-30 at 17 06 39](https://user-images.githubusercontent.com/11214093/40732957-784eb676-642c-11e8-918c-006ab59a8421.png)

![desired](https://user-images.githubusercontent.com/11214093/40733380-5c73733c-642d-11e8-9e44-4adff79c85ad.png)

The current line colour for Top Story Standalone (and could also update Top Story Landscape) is much darker than the other rules on ft.com and fights with the bullet points. If we could please update the border to 1px solid #ccc1b7 then it is easier for the reader to navigate and simplifies the patterns/colours used.

**Comment by notlee** [comment]
This is done and will be released in the next major, see: https://github.com/Financial-Times/o-teaser/pull/142

(sorry it went unnoticed for so long in your absence James!)
